services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    G3\FrameworkPractice\Application\MessageCommand\SayHello:
        tags: [g3.use_case]

    G3\FrameworkPractice\Application\Log\LogSummary:
        tags: [g3.use_case]

    G3\FrameworkPractice\Infrastructure\Log\LogSummaryConsole:

    G3\FrameworkPractice\Infrastructure\MessageCommand\HelloConsole:

    G3\FrameworkPractice\Infrastructure\UseCase\UseCaseSearcherConsole:

    G3\FrameworkPractice\Infrastructure\UseCase\UseCaseSearcher:
