services:
    _defaults:
      autowire: false
      autoconfigure: true
      public: false

    G3\FrameworkPractice\Application\MessageCommand\SayHello:

    G3\FrameworkPractice\Infrastructure\MessageCommand\HelloConsole:
        arguments:
            $sayMessage: '@G3\FrameworkPractice\Application\MessageCommand\SayHello'

    G3\FrameworkPractice\Application\Log\LogSummary:

    G3\FrameworkPractice\Infrastructure\Log\LogSummaryConsole:
