services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    G3\FrameworkPractice\Infrastructure\MessageCommand\HelloConsole:

    G3\FrameworkPractice\Infrastructure\Log\LogSummaryConsole:
