log_api:
    path: /log-summaries/{environment}
    defaults:
        environment: dev
    controller: G3\FrameworkPractice\Infrastructure\Endpoint\LogApiController::summaryLog
    methods: [GET]

log_api_post:
    path: /log-summaries/
    controller: G3\FrameworkPractice\Infrastructure\Endpoint\LogApiController::LogsOnMethodNotImplement
    methods: [POST]

log_api_patch:
    path: /log-summaries/
    controller: G3\FrameworkPractice\Infrastructure\Endpoint\LogApiController::LogsOnMethodNotImplement
    methods: [PATCH]

log_api_delete:
    path: /log-summaries/
    controller: G3\FrameworkPractice\Infrastructure\Endpoint\LogApiController::LogsOnMethodNotImplement
    methods: [DELETE]

log_api_put:
    path: /log-summaries/
    controller: G3\FrameworkPractice\Infrastructure\Endpoint\LogApiController::LogsOnMethodNotImplement
    methods: [PUT]
