monolog:
    handlers:
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        file_json:
            type: rotating_file
            formatter: json_log
            path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.json"
            level: debug
            max_files: 15
            channels: ["!event"]
