parameters:
    environment.name: 'ganianes_place'

    use.cases:
        - 'G3\FrameworkPractice\Application\MessageCommand\SayHello'
        - 'G3\FrameworkPractice\Infrastructure\Log\LogSummaryConsole'
