monolog:
    handlers:
        main:
            type: stream
            level: debug
            path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
