monolog:
    channels: ['external']
    handlers:
        filter_error:
            type: fingers_crossed
            action_level: error
            handler: file_json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!external"]
        external:
            type: rotating_file
            formatter: json_log
            path: "%kernel.logs_dir%/database/%kernel.environment%.json"
            level: debug
            max_files: 15
            channels: ["external"]
        file_json:
            type: rotating_file
            formatter: json_log
            path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.json"
            level: debug
            max_files: 15
            excluded_404s:
              - ^/
