monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: file_log
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%/%kernel.environment%.log"
            level: error
            excluded_404s:
                - ^/
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
