index:
    path: /
    controller: G3\FrameworkPractice\Infrastructure\Controller\MainController::showHelloEnvName

env_name:
    path: /env
    controller: G3\FrameworkPractice\Infrastructure\Controller\MainController::showHelloEnv
