index:
    path: /
    controller: G3\FrameworkPractice\Controller\MainController::showHelloEnvName

env_name:
    path: /env
    controller: G3\FrameworkPractice\Controller\MainController::showHelloEnv
